metadata:
  name: sysbench-cpu
  summary: sysbench-cpu is a subtest of SysBench benchmark suite to measure cpu performance.
  description: |-
    The cpu is one of the most simple benchmarks in SysBench. In this
    mode each request consists in calculation of prime numbers up to a
    value specified by the --cpu-max-primes option. All calculations
    are performed using 64-bit integers.
  homepage: https://github.com/akopytov/sysbench
type: workload
depends:
  debian@11:
  - sysbench
params:
  nr_threads:
  cpu_max_prime:
    doc: upper limit for primes generator
results:
  workload:
  latency_ms.max:
  latency_ms.min:
  latency_ms.avg:
  latency_ms.95th:
  events/thread.avg:
  events/thread.stddev:
  runtime/thread.avg:
  runtime/thread.stddev:
