metadata:
  name: will-it-scale
  summary: Will It Scale takes a testcase and runs it from 1 through to n parallel
    copies to see if the testcase will scale. It builds both a process and threads
    based test in order to see any differences between the two.
  description: |-
    Will It Scale takes a testcase and runs it from 1 through to n parallel copies
    to see if the testcase will scale. It builds both a process and threads based
    test in order to see any differences between the two.

    We rely on hwloc for a platform independent way of laying out tasks on cores.
    It can be found at www.open-mpi.org/projects/hwloc/.

    Care is taken to try and reduce run to run variability. By using hwloc we
    ensure each task is on its own core and won't get bounced around by the
    scheduler. The wrapper script (runtest.py) turns off address space
    randomisation which can cause huge differences in pagetable related benchmarks
    (one run may fit within one pte page, the next may span two). There is a
    warmup period before which an average is taken. The averaging period can be
    changed with the -s option, which by default is 5 seconds.
  homepage: https://github.com/antonblanchard/will-it-scale
type: workload
depends:
  debian@11:
  - python3-minimal
  - libhwloc-dev
  - linux-perf
params:
  runtime:
  test:
  mode:
    values:
    - process
    - thread
    - both
  nr_task:
  smt:
    values:
    - 0
    - 1
results:
  scalability:
  per_process_ops:
  per_thread_ops:
