metadata:
  name: unixbench
  summary: UnixBench is the original BYTE UNIX benchmark suite aims to test performance
    of Unix-like system.
  description: |-
    UnixBench is the original BYTE UNIX benchmark suite, updated and revised by
    many people over the years.

    The purpose of UnixBench is to provide a basic indicator of the performance of
    a Unix-like system; hence, multiple tests are used to test various aspects of
    the system's performance. These test results are then compared to the scores
    from a baseline system to produce an index value, which is generally easier to
    handle than the raw scores. The entire set of index values is then combined to
    make an overall index for the system.

    Some very simple graphics tests are included to measure the 2D and 3D graphics
    performance of the system.

    Multi-CPU systems are handled. If your system has multiple CPUs, the default
    behaviour is to run the selected tests twice -- once with one copy of each
    test program running at a time, and once with N copies, where N is the number
    of CPUs. This is designed to allow you to assess

      * the performance of your system when running a single task
      * the performance of your system when running multiple tasks
      * the gain from your system's implementation of parallel processing

    Do be aware that this is a system benchmark, not a CPU, RAM or disk benchmark.
    The results will depend not only on your hardware, but on your operating
    system, libraries, and even compiler.
  homepage: https://github.com/kdlucas/byte-unixbench
type: workload
depends:
  openeuler@22.03: unixbench
params:
  runtime:
  test:
  nr_task:
results:
  score:
    kpi: 1
    baseline: 10729
  Dhrystone_2_using_register_variables:
    kpi: 1
    baseline: 104210
  Double-Precision_Whetstone:
    kpi: 1
    baseline: 45043
  Execl_Throughput:
    kpi: 1
    baseline: 10645
  File_Copy_1024_bufsize_2000_maxblocks:
    kpi: 1
    baseline: 1895
  File_Copy_256_bufsize_500_maxblocks:
    kpi: 1
    baseline: 1248
  File_Copy_4096_bufsize_8000_maxblocks:
    kpi: 1
    baseline: 3653
  Pipe_Throughput:
    kpi: 1
    baseline: 19258
  Pipe-based_Context_Switching:
    kpi: 1
    baseline: 14736
  Process_Creation:
    kpi: 1
    baseline: 8788
  Shell_Scripts_(1_concurrent):
    kpi: 1
    baseline: 30139
  Shell_Scripts_(8_concurrent):
    kpi: 1
    baseline: 29397
  System_Call_Overhead:
    kpi: 1
    baseline: 2438
