metadata:
  name: unixbench
  summary: UnixBench is the original BYTE UNIX benchmark suite aims to test performance
    of Unix-like system.
  description: |-
    UnixBench is the original BYTE UNIX benchmark suite, updated and revised by
    many people over the years.

    The purpose of UnixBench is to provide a basic indicator of the performance of
    a Unix-like system; hence, multiple tests are used to test various aspects of
    the system's performance. These test results are then compared to the scores
    from a baseline system to produce an index value, which is generally easier to
    handle than the raw scores. The entire set of index values is then combined to
    make an overall index for the system.

    Some very simple graphics tests are included to measure the 2D and 3D graphics
    performance of the system.

    Multi-CPU systems are handled. If your system has multiple CPUs, the default
    behaviour is to run the selected tests twice -- once with one copy of each
    test program running at a time, and once with N copies, where N is the number
    of CPUs. This is designed to allow you to assess

      * the performance of your system when running a single task
      * the performance of your system when running multiple tasks
      * the gain from your system's implementation of parallel processing

    Do be aware that this is a system benchmark, not a CPU, RAM or disk benchmark.
    The results will depend not only on your hardware, but on your operating
    system, libraries, and even compiler.
  homepage: https://github.com/kdlucas/byte-unixbench
type: workload
depends:
  debian@11:
  - perl-base
  - perl
  - libperl-dev
  - make
params:
  runtime:
  test:
  nr_task:
results:
  score:
