metadata:
  name: autonuma-benchmark
  summary:
  description: ''
  homepage:
type: workload
depends:
  debian@11:
  - make
  - numactl
  - libnuma-dev
  - gcc
  - libc6-dev
  - gnuplot
  - gawk
  PKGBUILD:
  - autonuma-benchmark
params:
  test:
results:
