metadata:
  name: avocado
  summary:
  description: ''
  homepage:
type: workload
depends:
  debian@11:
  - build-essential
  - gcc
  - gdb
  - gdbserver
  - libc6-dev
  - make
  - python3
  - gawk
params:
  test_group:
results:
