#!/bin/bash

ospkg_update()
{
	$SUDO apt-get -q update
}

ospkg_install()
{
	# chronic is provided by deps/pack.cgz, but nfs rootfs + run_on_local_disk environment,
	# deps/pack.cgz will not be merged into the runtime rootfs currently.
	# one by one installation improve the installation success rate.
	if has_cmd chronic; then
		chronic=chronic
	else
		chronic=
	fi
	for package
	do
		$SUDO $chronic apt-get -o Dpkg::Options::=--force-confdef \
				 -o Dpkg::Options::=--force-confold \
				 install -q -y --no-upgrade $package >/tmp/apt-get_info 2>&1
		grep -v "dpkg: warning: files list file for package '.*' missing;" /tmp/apt-get_info
	done
}
