#!/bin/bash

ospkg_update()
{
	support_repo_epel
}

ospkg_install()
{
	local pkg nopkgs err
	for pkg
	do
		nopkgs=$(rpm --query $pkg | awk '{print $2}')
		[[ -n $nopkgs ]] || continue
		$SUDO yum install -y -q $nopkgs || err=$?
	done

	return $err
}
