#!/bin/bash

ospkg_update()
{
	support_repo_epel
}

ospkg_install()
{
	local pkg nopkgs err
	for pkg
	do
		nopkgs=$(rpm --query $pkg | awk '{print $2}')
		[[ -n $nopkgs ]] || continue
		$SUDO yum install -y -q $nopkgs || err=$?
	done

	return $err
}

ospkg_list()
{
	dnf list --all -q | cut -f1 -d. |
		grep -v -E '\-(doc|help|debuginfo|debugsource)$' | sort -u
}

support_repo_epel()
{
	if [ "${_system_name_lowercase}" = "centos" ] && ! rpm -q epel-release >/dev/null; then
		yum install -y epel-release >/dev/null 2>&1
	fi

	yum -q makecache --timer
}
