#!/bin/bash

ospkg_update()
{
	:
}

ospkg_install()
{
	local pkg nopkgs err
	for pkg
	do
		nopkgs=$(rpm --query $pkg | awk '{print $2}')
		[[ -n $nopkgs ]] || continue
		$SUDO zypper -q install -y $nopkgs || err=$?
	done

	return $err
}

ospkg_list()
{
	zypper packages | cut -f3 -d'|' | tr -d ' '| grep -A99999 '^[0-9]' |
		grep -v -E '\-(doc|help|debuginfo|debugsource)$' | sort -u
}
