#!/bin/bash

ospkg_update()
{
	:
}

ospkg_install()
{
	local pkg nopkgs
	for pkg
	do
		nopkgs=$(rpm --quiet --query $pkg | awk '{print $2}')
		[[ -n $nopkgs ]] &&
		$SUDO zypper -q install -y $nopkgs
	done
}
