#!/bin/sh

. $LKP_SRC/lib/detect-system.sh
arch=$(get_system_arch)

# enable i386 arch packages
[ "$arch" = "x86_64" ] && dpkg --add-architecture i386 && apt-get update
apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" \
     -o Dpkg::Options::="--force-overwrite" \
     -qq install $*
