metadata:
  name: idle
  summary: IDE for Python using Tkinter (default version)
  description: IDLE is an Integrated Development Environment for Python.IDLE is written
    using Tkinter and therefore quite platform-independent.
  homepage: https://www.python.org/
type: workload
depends:
params:
  idle_time:
results:
