#!/bin/bash
# - script
# - job

# Direct usage:
#
# job=stream.yaml tests/lkp-install-run
#
# cd tests
# script=stream ./lkp-install-run

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

cd $LKP_SRC || exit
make
lkp install

check_install_script()
{
	test -x $1 || return
	lkp install $1
}

check_install_job()
{
	test -f $1 || return
	local atomic_job=$(lkp split --any $1)
	atomic_job=${atomic_job##* ./}

	# don't run too long time
	sed -i 's/^runtime: [0-9].*/runtime: 10/' $atomic_job

	lkp install $atomic_job
	lkp run $atomic_job
}

if [[ $script ]]; then
	check_install_script monitors/$script
	check_install_script setup/$script
	check_install_script tests/$script
elif [[ $job ]]; then
	check_install_job jobs/$job
fi
