short_description: >
 The Phoronix Test Suite is the most comprehensive testing and benchmarking
 platform available that provides an extensible framework for which new tests
 can be easily added.

description: |
 The Phoronix Test Suite is the most comprehensive testing and benchmarking
 platform available for Linux, Solaris, Mac OS X, and BSD operating systems.
 The Phoronix Test Suite allows for carrying out tests in a fully automated
 manner from test installation to execution and reporting. All tests are meant
 to be easily reproducible, easy-to-use, and support fully automated execution.
 The Phoronix Test Suite is open-source under the GNU GPLv3 license and is
 developed by Phoronix Media in cooperation with partners. Version 1.0 of the
 Phoronix Test Suite was publicly released in 2008.

 The Phoronix Test Suite client itself is a test framework for providing
 seamless execution of test profiles and test suites. There are more than 200
 tests available by default, which are transparently available via
 OpenBenchmarking.org integration. Of these default test profiles there is a
 range of sub-systems that can be tested and a range of hardware from mobile
 devices to desktops and worksrtations/servers. New tests can be easily
 introduced via the Phoronix Test Suite's extensible test architecture, with
 test profiles consisting of XML files and shell scripts. Test profiles can
 produce a quantitative result or other qualitative/abstract results like image
 quality comparisons and pass/fail. Using Phoronix Test Suite modules, other
 data can also be automatically collected at run-time such as the system power
 consumption, disk usage, and other software/hardware sensors. Test suites
 contain references to test profiles to execute as part of a set or can also
 reference other test suites. Test suites are defined via an XML schema.

 Running the Phoronix Test Suite for the first time can be as simple as issuing
 a command such as phoronix-test-suite benchmark c-ray, which would proceed to
 install a simple CPU test, execute the test, and report the results. Along
 with the results, the system's hardware/software information is collected in a
 detailed manner, relevant system logs, and other important system attributes
 such as compiler flags and system state. Users can optionally upload their
 results to OpenBenchmarking.org for sharing results with others, comparing
 results against other systems, and to carry out further analysis.

homepage: http://www.phoronix-test-suite.com/

parameters:
 test:
 need_x:

results:
