short_description: >
 rcutorture is rcutorture kernel module load/unload test.

description: |
 The CONFIG_RCU_TORTURE_TEST config option is available for all RCU
 implementations.  It creates an rcutorture kernel module that can
 be loaded to run a torture test.  The test periodically outputs
 status messages via printk(), which can be examined via the dmesg
 command (perhaps grepping for "torture").  The test is started
 when the module is loaded, and stops when the module is unloaded.

 It is also possible to specify CONFIG_RCU_TORTURE_TEST=y, which will
 result in the tests being loaded into the base kernel.  In this case,
 the CONFIG_RCU_TORTURE_TEST_RUNNABLE config option is used to specify
 whether the RCU torture tests are to be started immediately during
 boot or whether the /proc/sys/kernel/rcutorture_runnable file is used
 to enable them.  This /proc file can be used to repeatedly pause and
 restart the tests, regardless of the initial state specified by the
 CONFIG_RCU_TORTURE_TEST_RUNNABLE config option.

homepage: https://www.kernel.org/doc/Documentation/RCU/torture.txt

parameters:
 runtime:
 test:
 rcutorture_type:

results:
