#!/bin/sh
# - test

. $LKP_SRC/lib/common.sh

[ -n "$test" ] || {
	echo "test is empty!" >&2
	exit 1
}

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/setup/drop_caches

cd /lkp/benchmarks/OSPerformance || exit
log_cmd python3 $test.py
log_cmd cp -r report/$test $TMP_RESULT_ROOT
