metadata:
  name: benchmark-sql-baseline
  summary:
  description:
  homepage:
type: workload
depends:
  PKGBUILD:
  - benchmark-sql-baseline
params:
  warehouses:
  loadworkers:
  terminals:
  runmins:
  runtxnsperterminal:
  limittxnspermin:
results:
