metadata:
  name: rt-app
  summary: rt-app is a test application that starts multiple periodic threads in order
    to simulate a real-time periodic load.
  description: |-
    rt-app is a test application that starts multiple periodic threads in order to
    simulate a real-time periodic load.
  homepage: https://github.com/scheduler-tools/rt-app
type: workload
depends:
  debian@11:
  - libjson11-1
  - numactl
params:
  workload:
results:
  run.average:
  run.stddev:
  period.average:
  period.stddev:
  slack.average:
  slack.stddev:
  wu_lat.average:
  wu_lat.stddev:
