metadata:
  name: iozone
  summary:
  description: ''
  homepage:
type: workload
depends:
  opensuse-leap@15.2:
  - iozone
  openeuler@20.03:
  - libtool  
params:
  block_size:
  file_size:
  test:
results:
