metadata:
  name: perf-bench-futex
  summary:
  description: ''
  homepage:
type: workload
depends:
params:
  runtime:
  nr_task:
  test:
  shared:
  futexes:
  nwakes:
  nwakers:
  nrequeue:
  multi:
results:
