metadata:
  name: ansible_test
  summary:
  description: ''
  homepage:
type: workload
depends:
  debian@11:
  - python3-pip
  - gcc
  - python3-dev
  - libffi-dev
  - libssl-dev
params:
  ansible_repo:
results:
