metadata:
  name: chromeswap
  summary: A program that emulates web browser workload to see the performance of
    the swap subsystem.
  description: |-
    Run basic performance benchmarks on compressed swap. Launches a number of "hog"
    processes that can be told to "balloon" (allocating a specified amount of memory
    in 1 MiB chunks) and can also be "poked", which reads from and writes to random
    places in memory to force swapping in and out. Hog processes report back statistics
    on how long a "poke" took (real and CPU time) and number of page faults.
  homepage: https://github.com/aaronlu/chromeswap.git
type: workload
depends:
  debian@11:
  - python3-numpy
  - libblas3
  PKGBUILD:
  - chromeswap
params:
  runtime:
    doc: limit run time to runtime seconds
  selection:
    doc: selection of function name (uniform/sequential/exponential)
  nr_procs:
    doc: Number of hog processes to use
  swap_targets:
    doc: Floating point value of target swap usage
results:
  throughput_swap_cycles_per_second:
