metadata:
  name: adrestia
  summary: A micro-benchmark to test scheduler load balancer
  description: ''
  homepage: https://github.com/mfleming/adrestia
type: workload
depends:
  debian@11:
  - clang
  PKGBUILD:
  - adrestia
params:
  arrival_rate:
    doc: arrival time (microseconds)
  num_loop:
    doc: number of loopsworkers per message thread
  service_time:
    doc: service time (microseconds)
  num_threads:
    doc: thread count
results:
  wakeup_cost_single_us:
  wakeup_cost_periodic_us:
