#!/bin/sh

. $LKP_SRC/lib/upload.sh
timeout=3600

server_log="/usr/share/oech/lib/server/results"
card_type=$test_card_type
card_name=$test_card_name
report="${card_type}-${card_name}-report.html"

function setup_oech_server() {
    systemctl start oech-server.service
    systemctl status oech-server.service
    systemctl start nginx.service
    systemctl stop firewalld
    iptables -F
    setenforce 0
}

function get_html_report() {
    for i in $(seq 0 ${timeout}); do
        ls ${server_log} | grep -v README
        if [[ $? -eq 0 ]]; then 
            break
        fi
        sleep 1
    done
    machine_name=$(ls ${server_log} | grep -v README)
    log_name=$(ls ${server_log}/${machine_name}/test | head -n 1)
    curl http://127.0.0.1/results/${machine_name}/test/${log_name} &>${report}
    sed -i "1,4d" ${card_name}.html
}

set -x

echo "Start to setup oech-server environment."

dnf install -y python3-devel oec-hardware-server

setup_oech_server

get_html_report

upload_files -t oec-hardware ${report}

echo "End to setup oech-server environment."

