metadata:
  name: perf-event-tests
  summary: The Perf Event Testsuite.
  description: This series of test is meant to validate that the perf_event subsystem
    is working.
  homepage: https://github.com/deater/perf_event_tests
type: workload
depends:
  debian@11:
  - libgomp1
  PKGBUILD:
  - perf-event-tests
params:
  paranoid:
results:
  perf_event_tests.throughput:
