metadata:
  name: makepkg
  summary: Arch Linux package build utility
  description: makepkg is a script to automate the building of packages. Therequirements
    for using the script are a build-capable *nix platformand a custom build script
    for each package you wish to build (knownas a PKGBUILD).
  homepage: https://archlinux.org/pacman/
type: workload
depends:
  debian@11:
  - curl
  - gnupg2
  - gettext
  - ncurses-bin
  - binutils
  - fakeroot
  - libarchive-tools
  - file
  - openssl
  - gawk
  - coreutils
  - findutils
  - grep
  - sed
  - gzip
  - bzip2
  - xz-utils
params:
  rootfs:
  benchmark:
  os:
  os_arch:
  os_version:
results:
