metadata:
  name: ebizzy
  summary: ebizzy is designed to generate a workload resembling common web application
    server workloads.
  description: |-
    ebizzy is designed to generate a workload resembling common web application
    server workloads. It is highly threaded, has a large in-memory working set,
    and allocates and deallocates memory frequently.
  homepage: http://ebizzy.sourceforge.net/
type: workload
depends: {}
params:
  nr_threads:
  duration:
  iterations:
results:
  throughput:
