short_description: >
 ebizzy is designed to generate a workload resembling common web application
 server workloads.

description: |
 ebizzy is designed to generate a workload resembling common web application
 server workloads. It is highly threaded, has a large in-memory working set,
 and allocates and deallocates memory frequently.

homepage: http://ebizzy.sourceforge.net/

parameters:
 nr_threads:
 duration:
 iterations:

results:
 ebizzy.throughput:
