metadata:
  name: bust_shm_exit
  summary: A small program to stress the shared memory exit path.
  description: Create a bunch of shared memory segments, then a bunch of threads that
    continually clone and exit.
  homepage: https://github.com/gaowanlong/bust_shm_exit
type: workload
depends: {}
params:
  runtime:
    doc: limit run time to runtime seconds
  segments:
    doc: the number of Shared Memory Segments
  nr_threads:
    doc: the number of threads
results:
  bust-shm-exit.pass: bust_shm_exit test done
  bust-shm-exit.fail: bust_shm_exit test exit with some error
