metadata:
  name: postmark
  summary: File system benchmark from NetApp
  description: 'Benchmark that''s based around small file operations similar to those
    used onlarge mail servers and news servers.  Has been ported to NT so should be
    goodfor comparing OSs. "Postmark: a new file system benchmark", Jeffrey Katcher,Network
    Appliance Technical Report TR-3022, October 1997'
  homepage:
type: workload
depends:
params:
  number:
  trans:
  subdirs:
results:
