short_description: >
 This is a test of EEMBC CoreMark processor benchmark.

description: |
 This is a test of EEMBC CoreMark processor benchmark
 to measures the performance of central processing units by 
 measuring the number of iteration (algo: CRC, list processing,
 matric manipulation, state machine ) per second.

homepage: https://www.eembc.org/coremark/

parameters:
 
results:
 coremark:iterations_per_sec: