metadata:
  name: kbuild
  summary: framework for writing simple makefiles for complex tasks
  description: The goals of the kBuild framework:- Similar behavior cross all supported
    platforms.- Flexibility, don't create unnecessary restrictions preventing ad-hocsolutions.-
    Makefile can very simple to write and maintain.
  homepage: https://svn.netlabs.org/kbuild
type: workload
depends:
params:
  nr_task:
  runtime:
  build_kconfig:
  target:
results:
