metadata:
  name: mutilate
  summary: mutilate - memcached load generator
  description: |-
    Mutilate is a memcached load generator designed for
    high request rates, good tail-latency measurements, and realistic
    request stream generation.
  homepage: https://github.com/leverich/mutilate
type: workload
depends:
  debian@11:
  - libzmq5
  - libevent-dev
  - memcached
  - libhugetlbfs-bin
  - libhugetlbfs-dev
params:
  master_threads:
    doc: number of thread in mutilate master
  agent_threads:
    doc: number of thread in mutilate agent
  runtime:
    doc: total runtime the benchmark run
results:
  read.avg:
  read.std:
  read.min:
  read.5th:
  read.10th:
  read.90th:
  read.95th:
  read.99th:
  update.avg:
  update.std:
  update.min:
  update.5th:
  update.10th:
  update.90th:
  update.95th:
  update.99th:
  op_q.avg:
  op_q.min:
  op_q.5th:
  op_q.10th:
  op_q.90th:
  op_q.95th:
  op_q.99th:
  totalqps:
  totalqps.total:
  totalqps.time:
  skipped.num:
  skipped.percent:
  misses.num:
  misses.percent:
  rx.bytes:
  rx.speed:
  tx.bytes:
  tx.speed:
