metadata:
        name: perf-c2c
        summary: Perf C2C monitor is aimed for capturing hot cache line miss
        description: |
            Perf C2C monitor is aimed for capturing hot cache line miss during the
            process of running workload, the total number of local/remote cache line
            HITM would be a very important performance metric to evaluate our
            optimzation work. Also, the top 3 cache lines ranked by HITM number
            should be given serious care as main optimization target.

            The first version of code refers to monitor/no-stdout/perf-profile.

            Usage: linux/tools/perf/Documentation/perf-c2c.txt

type: monitor
depends:
        openeuler@20.03: perf
        debian@11: linux-perf
params:
    event:
                doc: "[ldlat-loads|ldlat-stores] :: PMU event :: All as default"
    mode:
                doc: "[u|k] :: Track use space or kernel space events :: All as default"
    ldlat:
                doc: "[30|50|*] :: Configure mem-load latency :: 30 as default"
    delay:
                doc: "[15|20|*] :: Delay *N* seconds before sampling :: 100 as default, or half of runtime if runtime is set"
    duration:
                doc: "[10|20|*] :: Record sample within *N* seconds :: 10 as default"
