metadata:
  name: sysbench-memory
  summary: sysbench-memory is a subtest of SysBench benchmark suite to measure  memory
    performance.
  description: |-
    Sysbench memory benchmark will allocate a memory buffer and then read
    or write from it, each time for the size of a pointer(32bit or 64bit)
    until the total buffer size has been read from or written to. This is
    then repeated until the provided volume is reached. Users can provide
    multiple threads, different sizes in buffer and the type of requests.
  homepage: https://github.com/akopytov/sysbench
type: workload
depends:
  debian@11:
  - sysbench
params:
  nr_threads:
  mem_blk_size:
    doc: size of memory block for test
  mem_total_size:
    doc: total size of data to transfer
  mem_scope:
    doc: memory access scope
    values:
      - global
      - local
  mem_hugetlb:
    doc: allocate memory from HugeTLB pool
    values:
      - on
      - off
  mem_operation:
    doc: type of memory operations
    values:
      - read
      - write
      - none
  mem_access_mode:
    doc: memory access mode
    values:
      - seq
      - rnd
results:
  throughput_ops/s:
  throughput_MB/s:
  workload:
  latency_ms.max:
  latency_ms.min:
  latency_ms.avg:
  latency_ms.95th:
  events/thread.avg:
  events/thread.stddev:
  runtime/thread.avg:
  runtime/thread.stddev:
