metadata:
  name: rdma-pyverbs
  summary: Pyverbs provides a Python API over rdma-core, the Linux userspace C API
    for the RDMA stack. And rdma-pyverbs is the unitests for pyverbs.
  description: ''
  homepage: https://github.com/linux-rdma/rdma-core
type: workload
depends:
  debian@11:
  - libpython3.9
  - libnl-route-3-200
params: {}
results: {}
