metadata:
  name: perf-fuzzer
  summary: Perf fuzzer is a system call fuzzer specifically designed to find flaws
    in the complex Linux perf_event system call interface.
  description: ''
  homepage: https://github.com/deater/perf_event_tests/tree/master/fuzzer
type: workload
depends:
  debian@11:
  - libgomp1
params:
  runtime:
    doc: maximum running time of the test (seconds)
  seed:
    doc: seed random number generator with number
  number:
    doc: stop after number system calls
results: {}
