metadata:
  name: mcperf
  summary:
  description: ''
  homepage:
type: workload
depends:
  PKGBUILD:
  - mcperf
params:
  linger:
  timeout:
  testsize:
  conn_rate:
  call_rate:
  num_calls:
  num_conns:
results:
