metadata:
  name: stream
  summary:
  description:
  homepage:
type: workload
depends:
  PKGBUILD: stream
params:
results:
  add_bandwidth_MBps:
    kpi: 1
    baseline: 18165
  copy_bandwidth_MBps:
    kpi: 1
    baseline: 14882
  scale_bandwidth_MBps:
    kpi: 1
    baseline: 14783
  triad_bandwidth_MBps:
    kpi: 1
    baseline: 18262
