metadata:
  name: stream
  summary: 
  description:
  homepage:
type: workload
depends:
  PKGBUILD: stream
params:
results:
  copy_bandwidth_MBps:
    kpi: 1
  scale_bandwidth_MBps:
    kpi: 1
  add_bandwidth_MBps:
    kpi: 1
  triad_bandwidth_MBps:
    kpi: 1
