#!/bin/bash
# - nr_threads
# - array_size
# - omp
# - loop
# - iterations

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/reproduce-log.sh

log_cmd cd $BENCHMARK_ROOT/stream || die "can not enter $BENCHMARK_ROOT/stream"

log_cmd export OMP_NUM_THREADS=$nr_cpu
log_cmd export GOMP_CPU_AFFINITY=0-$(($nr_cpu-1))

[ -n "$array_size" ] || die "can not get array size"
[ -n "$omp" ] || die "can not get omp"
[ -n "$loop" ] || loop=100

[ "$omp" = "true" ] && omp_options="-fopenmp"

log_cmd gcc -O -DSTREAM_ARRAY_SIZE=$array_size stream.c -o stream ||
die "failed to compile stream"

for i in $(seq ${iterations:-1})
do
	echo Iteration: $i
	log_cmd ./stream || die "failed to run stream"
done
