metadata:
  name: build-ceph
  summary:
  description: ''
  homepage:
type: workload
depends:
  debian@11:
  - gcc
  - g++
  - bc
  - btrfs-progs
  - cmake
  - cpio
  - cryptsetup-bin
  - cython3
  - debhelper
  - default-jdk
  - dh-exec
  - dh-python
  - gdisk
  - git
  - gperf
  - javahelper
  - jq
  - junit4
  - libaio-dev
  - libbabeltrace-ctf-dev
  - libbabeltrace-dev
  - libblkid-dev
  - libcunit1-dev
  - libcurl4-openssl-dev
  - libexpat1-dev
  - libfuse-dev
  - libgoogle-perftools-dev
  - libibverbs-dev
  - librdmacm-dev
  - libkeyutils-dev
  - libldap2-dev
  - libleveldb-dev
  - liblttng-ust-dev
  - liblz4-dev
  - libnss3-dev
  - liboath-dev
  - libsnappy-dev
  - libssl-dev
  - libtool
  - libudev-dev
  - libxml2-dev
  - lsb-release
  - parted
  - pkg-config
  - python3
  - python3-all-dev
  - python3-cherrypy3
  - python3-nose
  - python3-pecan
  - python3-bcrypt
  - python3-six
  - tox
  - python3-coverage
  - python3-prettytable
  - python3-setuptools
  - python3-sphinx
  - python3-werkzeug
  - python3-all-dev
  - python3-setuptools
  - socat
  - uuid-dev
  - uuid-runtime
  - valgrind
  - virtualenv
  - xfslibs-dev
  - xfsprogs
  - xmlstarlet
  - yasm
  - zlib1g-dev
  - ragel
  - libhwloc-dev
  - libnuma-dev
  - libpciaccess-dev
  - libcrypto++-dev
  - libgnutls28-dev
  - libsctp-dev
  - libprotobuf-dev
  - protobuf-compiler
  - systemtap-sdt-dev
  - libyaml-cpp-dev
params:
  ceph_commit:
results:
