metadata:
  name: build-pkg
  summary:
  description: ''
  homepage:
type: workload
depends:
params:
  pkgbuild_repo:
  upstream_repo:
  upstream_commit:
  git_tag:
  pkg_ver:
  config:
  fetch_install:
results:
