#!/bin/sh -e
# - feature

[ -n "$feature" ] || exit 0

file="/sys/kernel/debug/sched/features"
[ -f $file ] || exit 0

. $LKP_SRC/lib/reproduce-log.sh

for f in $feature
do
	log_eval "echo $f > $file"
done

exit 0
