#!/bin/sh

# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

command -v firewall-cmd > /dev/null && systemctl $firewalld_action firewalld
