metadata:
  name: apachebench
  summary: apachebench is a tool for benchmarking your Apache Hypertext Transfer Protocol
    (HTTP) server.
  description: |-
    apachebench is a tool for benchmarking your Apache Hypertext Transfer Protocol
    (HTTP) server. It is designed to give you an impression of how your current
    Apache installation performs. This especially shows you how many requests per
    second your Apache installation is capable of serving.
  homepage: https://httpd.apache.org/docs/2.4/programs/ab.html
type: workload
depends:
  debian@11:
  - libssl1.1
  - apache2
  - libapache2-mpm-itk
params:
  runtime:
  concurrency:
results: {}
