metadata:
  name: intel-ipsec-mb
  summary:
  description: ''
  homepage:
type: workload
depends:
  fedora@32:
  - intel-ipsec-mb
params:
  algo:
  arch:
  job_size:
  job_iter:
  thread_count:
results:
