metadata:
  name: sysbench-threads-git
  summary:
  description:
  homepage:
type: workload
depends:
  PKGBUILD:
  - sysbench-threads-git
params:
  nr_threads:
  thread_yields:
  thread_locks:
results:
