metadata:
  name: dd
  summary: Test writeback performance.
  description: Copy a file, converting and formatting according to the operands.
  homepage:
type: workload
depends:
  debian@11:
  - psmisc
params:
  runtime:
    doc: limit run time to runtime seconds
  disk:
    doc: specify HDD/SDD disk to be used
  md:
    doc: use mdadm to create raid_device
  iosched:
    doc: select an IO scheduler
  fs:
    doc: specify the file system
  nr_threads:
    doc: The number of threads that will run dd
results:
  startup_time_ms:
  kill_time_ms:
  rm_time_ms:
