metadata:
  name: boards-scan
  summary:
  description:
  homepage:
type: workload
depends:
  debian@11:
    - dmidecode
    - lshw
    - util-linux # lscpu
    - pciutils   # lspci
    - facter
params:
results:
