metadata:
  name: sysbench-mutex
  summary: sysbench-mutex is a subtest of SysBench benchmark suite to measure performance
    of mutex implementation.
  description: |-
    This test mode was written to emulate a situation when all threads
    run concurrently most of the time, acquiring the mutex lock only
    for a short period of time (incrementing a global variable).
  homepage: https://github.com/akopytov/sysbench
type: workload
depends:
params:
  nr_threads:
  mutex_num:
    doc: total size of mutex array
  mutex_locks:
    doc: number of mutex locks to do per thread
  mutex_loops:
    doc: number of empty loops to do inside mutex lock
results:
  workload:
  latency_ms.max:
  latency_ms.min:
  latency_ms.avg:
  latency_ms.95th:
  events/thread.avg:
  events/thread.stddev:
  runtime/thread.avg:
  runtime/thread.stddev:
