#!/bin/bash
# - script
# - job

# Direct usage:
#
# job=stream.yaml tests/lkp-install-run
#
# cd tests
# script=stream ./lkp-install-run

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

. $LKP_SRC/lib/lkp_path.sh

cd $LKP_SRC || exit
sbin/install-dependencies.sh

check_install_script()
{
	test -x $1 || return
	lkp install $1
}

check_install_job()
{
	find_job "$1" || return
	local atomic_job=$(lkp split --any $job_file)
	atomic_job=${atomic_job##* ./}

	# don't run too long time
	sed -i 's/^runtime: [0-9].*/runtime: 3/' $atomic_job

	lkp install $atomic_job
	lkp run $atomic_job
}

if [[ $script ]]; then
	check_install_script $script
elif [[ $job ]]; then
	check_install_job $job
fi
